### ISSUE TITLE
Fails to compile in node 0.12.0

### ISSUE THREAD

**Issue by BryanDonovan** [cainus/Prozess#52]
I get this on mac os 10.10.2 when running `npm install prozess`:

```
                                   v8::internal::Arguments
/Users/bdonovan/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:206:36: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Upowm(const Arguments& args);
                                   ^~~~~~~~~
```
